### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by Katka92**
Fixing functional tests.

### CODE REVIEW

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
Tests are now failing mainly because of timeout. I would like to merge this PR. @rhopp @ScrewTSW could you review?

**Comment by rhopp** [comment]
@Katka92 Didi you investigate the origin of these timeouts? Maybe the user accounts just needs to be cleaned up (you know... the issue with slow mount of PVCs...)

**Comment by Katka92** [comment]
@rhopp I haven't investigate it yet, I will take a look, but I think it is not related with changes made in this PR. Cleaning user accounts seems like it could solve that, but need more investigation.

**Pull request merged**
