### PR TITLE
Workspace creation test

### PR DESCRIPTION
**Pull request by Katka92**
Test creation of second workspace if one is already running. Producer for CheWorkspaceProvider was created to produce configuration variables.

### CODE REVIEW

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ppitonak** [comment]
@rhopp please review

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ppitonak** [comment]
Do you know why Jenkins job failed?

**Comment by rhopp** [comment]
@Katka92 could you please rebase to master (solve conflicts) and in places where it would make sense squash some commits, so we don't have so many commits in PR (ideally 1-2 commits per PR ;-)). Thanks.

**Pull request merged**
