### PR TITLE
WIP Change URL for retreving OS token.

### PR DESCRIPTION
**Pull request by Katka92**
URL has changed. This inflicted prepare_environment.sh file.

### CODE REVIEW

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
@rhopp can you review please? :)

**Comment by rhopp** [comment]
We have the `OSO_MASTER_URL` variable stored in `config` file, which we are sourcing later in the process. What about moving whole `# Load configuration` section (https://github.com/redhat-developer/che-functional-tests/blob/master/cico_run_EE_tests.sh#L9-L19) before executing `prepare_environment.sh`? I think this should not break anything and it would allow us to use `OSO_MASTER_URL` in `prepare_environment.sh`. WDYT? Can it break something?

**Comment by Katka92** [comment]
Yeah, it didn't break anything and it is surely better. Thanks!

**Pull request merged**
