### PR TITLE
Do not merge!

### PR DESCRIPTION
**Pull request by rhopp**
This PR/commit is just for starting tests on ci.centos.org

Signed-off-by: Radim Hopp <rhopp@redhat.com>

### CODE REVIEW

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Pull request closed without merging**
